<svg xmlns="http://www.w3.org/2000/svg" width="44" height="43" viewBox="0 0 44 43">
    <g>
        <g>
            <path fill="none" stroke="#14214e" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="20"
                stroke-width="2"
                d="M5.276 14.7v0h25.14c1.753 0 3.107 1.583 2.808 3.321l-2.081 9.763a1.42 1.42 0 0 1-1.397 1.169H8.838v0" />
        </g>
        <g>
            <path fill="none" stroke="#14214e" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="20"
                stroke-width="2" d="M9.551 38.929a2.85 2.85 0 1 1 5.7 0 2.85 2.85 0 0 1-5.7 0z" />
        </g>
        <g>
            <path fill="none" stroke="#14214e" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="20"
                stroke-width="2" d="M25.228 38.929a2.85 2.85 0 1 1 5.701 0 2.85 2.85 0 0 1-5.7 0z" />
        </g>
        <g>
            <path fill="none" stroke="#14214e" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="20"
                stroke-width="2"
                d="M1 9c2.85 0 2.85 1.425 4.276 5.7L9.55 31.804c.141.657.48 1.425 1.152 1.425h20.226v0" />
        </g>
    </g>
    <g>
        <path fill="#c70041"
            d="M21 11.264C21 5.043 26.043 0 32.264 0c6.22 0 11.263 5.043 11.263 11.264 0 6.22-5.042 11.263-11.263 11.263S21 17.485 21 11.264z" />
    </g>
    <g>
        <g>
            <text fill="#fff" style="font-kerning:normal" dominant-baseline="text-before-edge"
                font-family="'Source Sans Pro','SourceSansPro-Bold'" font-size="16" font-style="none"
                font-weight="700" transform="translate(28)">
                <tspan>3</tspan>
            </text>
        </g>
    </g>
</svg>
